export const data = [
  {
    collectionName: 'Modern',
    products: [
      {
        productId: 28,
        productName: 'Rumah Modern',
        productCollection: 'Modern',
        productType: 'Rumah',
        productDescription: 'Rumah Modern',
        productPrice: 32432342,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/3aU4oBUxb6_1661564090618.png',
        ],
      },
      {
        productId: 35,
        productName: 'Rumah Modern 2',
        productCollection: 'Modern',
        productType: 'Rumah',
        productDescription: 'Rumah Modern 2',
        productPrice: 312124124,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/zzCjqnBA3X_1661564347113.png',
        ],
      },
      {
        productId: 36,
        productName: 'Rumah Modern 3',
        productCollection: 'Modern',
        productType: 'Rumah',
        productDescription: 'Rumah Modern 3',
        productPrice: 312124124,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/rtbiTdhtpW_1661564354856.png',
        ],
      },
      {
        productId: 39,
        productName: 'Rumah Modern 6',
        productCollection: 'Modern',
        productType: 'Rumah',
        productDescription: 'Rumah Modern 6',
        productPrice: 313244214,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/UMXP6R0Vai_1661564477704.png',
        ],
      },
      {
        productId: 40,
        productName: 'Rumah Modern 7',
        productCollection: 'Modern',
        productType: 'Rumah',
        productDescription: 'Rumah Modern 7',
        productPrice: 313244214,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/2RaJGJZNTL_1661564490414.png',
        ],
      },
      {
        productId: 41,
        productName: 'Rumah Modern 8',
        productCollection: 'Modern',
        productType: 'Rumah',
        productDescription: 'Rumah Modern 8',
        productPrice: 313244214,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/x4cJONZ9Q5_1661564506148.png',
        ],
      },
    ],
  },
  {
    collectionName: 'Minimalis',
    products: [
      {
        productId: 29,
        productName: 'Rumah Minimalis',
        productCollection: 'Minimalis',
        productType: 'Rumah',
        productDescription: 'Rumah Minimalis',
        productPrice: 243241343,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/WtY5DqV6yk_1661564211448.png',
        ],
      },
      {
        productId: 30,
        productName: 'Rumah Minimalis 2',
        productCollection: 'Minimalis',
        productType: 'Rumah',
        productDescription: 'Rumah Minimalis 2',
        productPrice: 243241343,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/LHaPQ5VTDu_1661564240383.png',
        ],
      },
      {
        productId: 31,
        productName: 'Rumah Minimalis 3',
        productCollection: 'Minimalis',
        productType: 'Rumah',
        productDescription: 'Rumah Minimalis 3',
        productPrice: 243241343,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/XGMhiLjCln_1661564250870.png',
        ],
      },
      {
        productId: 32,
        productName: 'Rumah Minimalis 4',
        productCollection: 'Minimalis',
        productType: 'Rumah',
        productDescription: 'Rumah Minimalis 4',
        productPrice: 243241343,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/26yM4sDzPx_1661564261984.png',
        ],
      },
      {
        productId: 33,
        productName: 'Rumah Minimalis 5',
        productCollection: 'Minimalis',
        productType: 'Rumah',
        productDescription: 'Rumah Minimalis 5',
        productPrice: 243241343,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/Dtaf0QfIlw_1661564275531.png',
        ],
      },
      {
        productId: 34,
        productName: 'Rumah Minimalis 6',
        productCollection: 'Minimalis',
        productType: 'Rumah',
        productDescription: 'Rumah Minimalis 6',
        productPrice: 243241343,
        productStatus: 'ON LISTING',
        designPhotos: [
          'https://storage.googleapis.com/fp-jj-fwdb.appspot.com/images/kuej7EwtGL_1661564284153.png',
        ],
      },
    ],
  },
];
